version: '3'
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: template
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: air -c .air.toml
    tty: true
    stdin_open: true
    ports:
      - '5001:5001'
    volumes:
      - ./app:/go/src/go-gqlgen-template
      - pkg:/go/pkg
volumes:
  pkg:
    driver: local
